lakion_cms_shop_static_content_show:
    path: /{name}
    methods: [GET]
    defaults:
        _controller: lakion_cms.controller.static_content:showAction
        _sylius:
            template: "@LakionCmsPlugin/Shop/StaticContent/show.html.twig"
            repository:
                method: findPublishedOneByName
                arguments: [$name]

cmf_media_file:
    resource: "@CmfMediaBundle/Resources/config/routing/file.xml"

cmf_media_image:
    resource: "@CmfMediaBundle/Resources/config/routing/image.xml"

_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.yaml"
